name: CI/CD Pipeline

on:
  push:
    branches: [ main, feature_8 ]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка исходного кода
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt flake8

      - name: Запуск линтера (Проверка стиля кода)
        run: |
          # Проверяем синтаксические ошибки Python
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Запуск тестов проекта
        env:
          SECRET_KEY: 'django-insecure-test-key-for-github-actions-pipeline'
        run: |
          python manage.py test
  

  deploy:
    runs-on: ubuntu-latest
    needs: test_and_lint
    steps:
      - name: Проверка исходного кода
        uses: actions/checkout@v3

      - name: Деплой по SSH-ключу
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p /app/project_5 && cd /app/project_5
            
            if ! command -v docker &> /dev/null; then
              apt-get update && apt-get install -y docker.io docker-compose
            fi
            
            if [ ! -d ".git" ]; then
              git clone https://github.com{{ github.repository }}.git .
            else
              git pull origin feature_5
            fi
            
            # Автоматически создаем .env файл на сервере из секретов GitHub для безопасности
            echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" > .env
            echo "CELERY_BROKER_URL=redis://redis:6379/0" >> .env
            echo "CELERY_RESULT_BACKEND=redis://redis:6379/0" >> .env
            
            docker-compose down
            docker-compose up --build -d
